package com.app.modules.reports.repository;

import com.app.modules.reports.entity.Report;
import com.app.modules.reports.enums.ReportType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Repository interface for Report entity.
 */
@Repository
public interface ReportRepository extends JpaRepository<Report, Integer> {

    /**
     * Find all reports generated by a specific user, ordered by generated date descending.
     */
    List<Report> findByGeneratedByOrderByGeneratedDateDesc(Integer generatedBy);

    /**
     * Find all reports by report type, ordered by generated date descending.
     */
    List<Report> findByReportTypeOrderByGeneratedDateDesc(ReportType reportType);

    /**
     * Find all reports by department, ordered by generated date descending.
     */
    List<Report> findByDepartmentOrderByGeneratedDateDesc(String department);
}
