package com.uniconnect.student.modules.reports.controller;

import com.uniconnect.student.common.dto.ApiResponseDTO;
import com.uniconnect.student.modules.reports.dto.ReportRequestDTO;
import com.uniconnect.student.modules.reports.dto.ReportResponseDTO;
import com.uniconnect.student.modules.reports.service.ReportService;
import jakarta.validation.Valid;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST Controller for Report Generation operations.
 * Provides endpoints for generating and retrieving reports.
 */
@RestController
@RequestMapping("/api/reports")
public class ReportController {

    private final ReportService reportService;

    public ReportController(ReportService reportService) {
        this.reportService = reportService;
    }

    /**
     * Generate a new report based on provided parameters.
     *
     * POST /api/reports/generate
     *
     * @param requestDTO the report generation parameters
     * @return the generated report details
     */
    @PostMapping("/generate")
    public ResponseEntity<ApiResponseDTO<ReportResponseDTO>> generateReport(
            @Valid @RequestBody ReportRequestDTO requestDTO) {

        ReportResponseDTO responseDTO = reportService.generateReport(requestDTO);

        ApiResponseDTO<ReportResponseDTO> response = ApiResponseDTO.success(
                "Report generated successfully", responseDTO);

        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    /**
     * Get all reports generated by a specific user.
     *
     * GET /api/reports/user/{userId}
     *
     * @param userId the user ID
     * @return list of report records
     */
    @GetMapping("/user/{userId}")
    public ResponseEntity<ApiResponseDTO<List<ReportResponseDTO>>> getReportsByUser(
            @PathVariable("userId") Integer userId) {

        List<ReportResponseDTO> reports = reportService.getReportsByUser(userId);

        ApiResponseDTO<List<ReportResponseDTO>> response = ApiResponseDTO.success(
                "Reports retrieved successfully", reports);

        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * Get a specific report by ID.
     *
     * GET /api/reports/{reportId}
     *
     * @param reportId the report ID
     * @return the report details
     */
    @GetMapping("/{reportId}")
    public ResponseEntity<ApiResponseDTO<ReportResponseDTO>> getReportById(
            @PathVariable("reportId") Integer reportId) {

        ReportResponseDTO responseDTO = reportService.getReportById(reportId);

        ApiResponseDTO<ReportResponseDTO> response = ApiResponseDTO.success(
                "Report retrieved successfully", responseDTO);

        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    /**
     * Get all reports in the system.
     *
     * GET /api/reports
     *
     * @return list of all report records
     */
    @GetMapping
    public ResponseEntity<ApiResponseDTO<List<ReportResponseDTO>>> getAllReports() {

        List<ReportResponseDTO> reports = reportService.getAllReports();

        ApiResponseDTO<List<ReportResponseDTO>> response = ApiResponseDTO.success(
                "All reports retrieved successfully", reports);

        return new ResponseEntity<>(response, HttpStatus.OK);
    }
}
