package com.app.modules.reports.serviceImpl;

import com.app.common.exception.ResourceNotFoundException;
import com.app.common.exception.UnauthorizedAccessException;
import com.app.modules.reports.dto.ReportRequestDTO;
import com.app.modules.reports.dto.ReportResponseDTO;
import com.app.modules.reports.entity.Report;
import com.app.modules.reports.enums.ReportFormat;
import com.app.modules.reports.enums.ReportType;
import com.app.modules.reports.exception.InvalidDateRangeException;
import com.app.modules.reports.exception.ReportGenerationException;
import com.app.modules.reports.repository.ReportRepository;
import com.app.modules.reports.service.ReportService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Implementation of ReportService.
 * Handles business logic for report generation and retrieval operations.
 */
@Service
public class ReportServiceImpl implements ReportService {

    private final ReportRepository reportRepository;

    @Value("${file.reports-dir:uploads/reports}")
    private String reportsDir;

    public ReportServiceImpl(ReportRepository reportRepository) {
        this.reportRepository = reportRepository;
    }

    /**
     * Generate a report based on the provided parameters.
     * Validates user authorization, date range, and generates the report file.
     */
    @Override
    public ReportResponseDTO generateReport(ReportRequestDTO requestDTO) {

        // Validate date range
        LocalDate startDate = LocalDate.parse(requestDTO.getStartDate());
        LocalDate endDate = LocalDate.parse(requestDTO.getEndDate());

        if (!endDate.isAfter(startDate)) {
            throw new InvalidDateRangeException(
                    "End date must be later than start date. Start: " + startDate + ", End: " + endDate);
        }

        // Parse enums
        ReportType reportType = ReportType.valueOf(requestDTO.getReportType());
        ReportFormat reportFormat = ReportFormat.valueOf(requestDTO.getReportFormat());

        // Generate the report file
        String filePath = generateReportFile(requestDTO.getUserId(), reportType, reportFormat,
                startDate, endDate, requestDTO.getDepartment());

        // Create and save the report record
        Report report = new Report();
        report.setGeneratedBy(requestDTO.getUserId());
        report.setReportType(reportType);
        report.setStartDate(startDate);
        report.setEndDate(endDate);
        report.setDepartment(requestDTO.getDepartment() != null ? requestDTO.getDepartment() : "All Departments");
        report.setReportFormat(reportFormat);
        report.setFilePath(filePath);

        Report savedReport = reportRepository.save(report);

        return mapToResponseDTO(savedReport);
    }

    /**
     * Get all reports generated by a specific user.
     */
    @Override
    public List<ReportResponseDTO> getReportsByUser(Integer userId) {
        List<Report> reports = reportRepository.findByGeneratedByOrderByGeneratedDateDesc(userId);

        return reports.stream()
                .map(this::mapToResponseDTO)
                .collect(Collectors.toList());
    }

    /**
     * Get a specific report by its ID.
     */
    @Override
    public ReportResponseDTO getReportById(Integer reportId) {
        Report report = reportRepository.findById(reportId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "Report not found with ID: " + reportId));

        return mapToResponseDTO(report);
    }

    /**
     * Get all reports in the system.
     */
    @Override
    public List<ReportResponseDTO> getAllReports() {
        List<Report> reports = reportRepository.findAll();

        return reports.stream()
                .map(this::mapToResponseDTO)
                .collect(Collectors.toList());
    }

    /**
     * Generate the report file and return its file path.
     */
    private String generateReportFile(Integer userId, ReportType reportType, ReportFormat reportFormat,
                                       LocalDate startDate, LocalDate endDate, String department) {

        // Ensure reports directory exists
        File directory = new File(reportsDir);
        if (!directory.exists()) {
            directory.mkdirs();
        }

        // Generate file name
        String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
        String extension = reportFormat == ReportFormat.PDF ? ".pdf" : ".xlsx";
        String fileName = reportType.name().toLowerCase() + "_" + timestamp + "_user" + userId + extension;
        String filePath = reportsDir + File.separator + fileName;

        // Generate report content
        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write("Report Type: " + reportType.getDisplayName() + "\n");
            writer.write("Generated By: User " + userId + "\n");
            writer.write("Date Range: " + startDate + " to " + endDate + "\n");
            writer.write("Department: " + (department != null ? department : "All Departments") + "\n");
            writer.write("Generated On: " + LocalDateTime.now() + "\n");
            writer.write("Format: " + reportFormat.getDisplayName() + "\n");
            writer.write("\n--- Report Data ---\n");
            writer.write("This is a generated report placeholder.\n");
            writer.write("In production, this would contain aggregated data from the database.\n");
        } catch (IOException e) {
            throw new ReportGenerationException(
                    "Failed to generate report file: " + e.getMessage());
        }

        return filePath;
    }

    /**
     * Map Report entity to ReportResponseDTO.
     *
     * @param report the entity to map
     * @return the response DTO
     */
    private ReportResponseDTO mapToResponseDTO(Report report) {
        return ReportResponseDTO.builder()
                .reportId(report.getReportId())
                .generatedBy(report.getGeneratedBy())
                .reportType(report.getReportType().getDisplayName())
                .startDate(report.getStartDate())
                .endDate(report.getEndDate())
                .department(report.getDepartment())
                .reportFormat(report.getReportFormat().getDisplayName())
                .filePath(report.getFilePath())
                .generatedDate(report.getGeneratedDate())
                .build();
    }
}
