package com.app.modules.reports.service;

import com.app.modules.reports.dto.ReportRequestDTO;
import com.app.modules.reports.dto.ReportResponseDTO;

import java.util.List;

/**
 * Service interface for Report Generation operations.
 */
public interface ReportService {

    /**
     * Generate a report based on the provided parameters.
     *
     * @param requestDTO the report generation parameters
     * @return the generated report details
     */
    ReportResponseDTO generateReport(ReportRequestDTO requestDTO);

    /**
     * Get all reports generated by a specific user.
     *
     * @param userId the user ID
     * @return list of report records
     */
    List<ReportResponseDTO> getReportsByUser(Integer userId);

    /**
     * Get a specific report by its ID.
     *
     * @param reportId the report ID
     * @return the report details
     */
    ReportResponseDTO getReportById(Integer reportId);

    /**
     * Get all reports in the system.
     *
     * @return list of all report records
     */
    List<ReportResponseDTO> getAllReports();
}
